### PR TITLE
Fixes examples

### PR DESCRIPTION
**Pull request by joestrong**
The examples were broken (I presume the NPM website changed its markup), so I've fixed them

### CODE REVIEW

**Comment by masterT** [comment]
@joestrong there is conflicts because I merged the PR #8.

**Comment by joestrong** [comment]
Cheers, I can fix that up later

**Comment by masterT** [comment]
I tested the examples everything is good! Thank you! 😄

**Comment by joestrong** [comment]
@masterT Have resolved the conflicts :+1:

**Pull request merged**
